import type { Metadata } from 'next'
import Head from 'next/head'
import './globals.css'
import { Bebas_Neue } from 'next/font/google'

const bebasNeue = Bebas_Neue({
	weight: '400',
	subsets: ['latin', 'latin-ext'],
	preload: true,
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<Head>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no'
				/>
			</Head>
			<body className={bebasNeue.className}>{children}</body>
		</html>
	)
}
