import type { Metadata } from 'next'
import './globals.css'
import { Bebas_Neue } from 'next/font/google'

const inter = Bebas_Neue({ weight: '400' })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>{children}</body>
		</html>
	)
}
